#!/bin/bash

# md_d, for performing a molecular dynamics simulation using GROMACS in double precision.
# Tested using GROMACS 4.5.4.

# Directory of this script.
DIR=`dirname $0`/

# Input files.
INPUT_RUNFILE=${DIR}md.mdp
INPUT_CONFORMATION=$1
INPUT_TOPOLOGY=$2

# Output files.
OUTPUT_TRAJECTORY=output.xtc
OUTPUT_ENERGY=output.edr

# Temporary files.
TEMP_MDP=temp.mdp
TEMP_TPR=temp.tpr
TEMP_CPT=temp.cpt
TEMP_GRO=temp.gro
TEMP_LOG=temp.log

# Avoid GROMACS backup files.
export GMX_MAXBACKUP=-1

# Create run file.
grompp_d -f $INPUT_RUNFILE -po $TEMP_MDP -c $INPUT_CONFORMATION -p $INPUT_TOPOLOGY -o $TEMP_TPR > /dev/null

# Execute run file.
mdrun_d -s $TEMP_TPR -x $OUTPUT_TRAJECTORY -cpo $TEMP_CPT -c $TEMP_GRO -e $OUTPUT_ENERGY -g $TEMP_LOG > /dev/null
